handler: FederatedFinetuneTrainer
method_args:
  num_clients: 3  # Total number of clients in federated learning
  aggregation_strategy: "FedAdam"  # FedAvg, FedAdam, FedYogi, FedAdagrad, FedAvgM
  global_rounds: 2  # Total number of global training rounds

args:
  output_dir: saves/finetune/${task_name}
  logging_dir: ${trainer.args.output_dir}/logs
  per_device_train_batch_size: 32  # Reduce batch size to lower memory usage
  per_device_eval_batch_size: 1   # Reduce evaluation batch size
  gradient_accumulation_steps: 1  # Increase gradient accumulation steps to maintain effective batch size
  learning_rate: 8e-5
  bf16: True
  bf16_full_eval: True
  logging_steps: 5
  report_to: tensorboard
  ddp_find_unused_parameters: None
  gradient_checkpointing: False  # Disable gradient checkpointing to address LoRA compatibility issues
  optim: paged_adamw_32bit
  save_strategy: 'no'
  save_only_model: True
  weight_decay: 0.01
  do_train: True
  do_eval: False
  eval_on_start: False
  eval_strategy: 'no'
  num_train_epochs: 10
  seed: 0