# 联邦未学习训练器配置
type: FederatedUnlearningTrainer

# 联邦学习参数
num_clients: 5  # 客户端数量
target_client_idx: 0  # 目标客户端索引（包含遗忘数据的客户端）
client_epochs: 2  # 每轮联邦学习中，每个客户端训练的轮数
aggregation_strategy: fedavg  # 模型聚合策略，目前支持fedavg

# 差分隐私设置
privacy_enabled: false  # 是否启用差分隐私
noise_multiplier: 0.1  # 噪声乘数，越大隐私保护越强，但准确性降低
max_grad_norm: 1.0  # 梯度裁剪的最大范数

# 训练参数
training_args:
  output_dir: ./output/federated_unlearned  # 输出目录
  per_device_train_batch_size: 8  # 每个设备的训练批次大小
  per_device_eval_batch_size: 8  # 每个设备的评估批次大小
  learning_rate: 2.0e-5  # 学习率
  weight_decay: 0.01  # 权重衰减
  num_train_epochs: 3  # 训练轮数（此为每个客户端的本地训练轮数）
  gradient_accumulation_steps: 1  # 梯度累积步数
  lr_scheduler_type: linear  # 学习率调度器类型
  warmup_ratio: 0.1  # 预热比例
  logging_steps: 10  # 日志记录步数
  eval_steps: 50  # 评估步数
  save_steps: 500  # 保存步数
  evaluation_strategy: steps  # 评估策略
  load_best_model_at_end: true  # 结束时加载最佳模型
  save_total_limit: 2  # 保存的检查点总数
  fp16: true  # 是否使用混合精度
  report_to: tensorboard  # 报告后端
  dataloader_num_workers: 2  # 数据加载器的工作线程数
  disable_tqdm: false  # 是否禁用进度条
  remove_unused_columns: false  # 是否移除未使用的列
  label_names: [labels]  # 标签名称

# 评估指标
metrics:
  accuracy:
    type: accuracy
  precision:
    type: precision
  recall:
    type: recall
  f1:
    type: f1 