handler: FinetuneTrainer
args:
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 1
  learning_rate: 8e-5
  bf16: True
  bf16_full_eval: True
  logging_steps: 5
  output_dir: ${paths.output_dir}
  logging_dir: ${trainer.args.output_dir}/logs
  report_to: tensorboard
  ddp_find_unused_parameters: None
  gradient_checkpointing: False
  optim: paged_adamw_32bit
  save_strategy: 'no'
  save_only_model: True
  weight_decay: 0.01
  do_train: True
  do_eval: False
  eval_on_start: False
  eval_strategy: 'no'
  num_train_epochs: 2
  seed: 0