defaults:
  - model: Llama-3.2-1B-Instruct-lora
  - trainer: FederatedFinetune
  - data: finetune
  - collator: DataCollatorForSupervisedDataset
  - eval: tofu
  - hydra: default
  - paths: default
  - experiment: null
  - _self_

trainer:
  args: 
    remove_unused_columns: False

mode: train
task_name: ??? 